export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<header
					style={{
						padding: '1rem',
						backgroundColor: 'lightblue',
					}}>
					<p>Header</p>
				</header>

				{children}

				<footer
					style={{
						backgroundColor: 'ghostwhite',
						padding: '1rem',
					}}>
					<p>Footer</p>
				</footer>
			</body>
		</html>
	);
}
